### PR TITLE
Remove yang 2 rfc8366

### PR DESCRIPTION
**Pull request by mcr**
This removes all the YANG/voucher content from constrained-voucher to rfc8366bis.

### CODE REVIEW

**Comment by EskoDijk** [comment]
Thanks! Because the rfc8366bis now also defines the CBOR serialization and the SIDs, some wording needs to be adapted to point to this document for the CBOR details. I can do some commits to this PR to adapt the text for that, ok?

**Comment by EskoDijk** [comment]
@mcr I've just added a commit with my proposed changes. The rest looks good (the parts already removed/changed)

**Comment by mcr** [comment]
> Thanks! Because the rfc8366bis now also defines the CBOR serialization and the SIDs, some wording needs to be adapted to point to this document for the CBOR details. I can do some commits to this PR to adapt the text for that, ok?

Yeah, we are going to have to go through each document and adjust a whole bunch of things.

**Comment by EskoDijk** [comment]
> Yeah, we are going to have to go through each document and adjust a whole bunch of things
Round 1 of this adjusting things I already did ;-)

**Review by EskoDijk — APPROVED** [review]
Ok, can be merged now. Thanks

**Comment by EskoDijk** [comment]
@mcr I'll merge the changes in this week, if no further objections. We can then produce a new I-D before the submission deadline.

**Pull request merged**
